#coding:utf-8

class PARAM_NAMESPACE:
    sTimestamp = "Timestamp"
    sInstantPue = "InstantPue"
    sItElectricPower = "ItElectricPower"
    sTotalElectricPower = "TotalElectricPower"
    sItElectricTotalWork = "ItElectricTotalWork"
    sTotalElectricTotalWork = "TotalElectricTotalWork"
    sAcOnoffStatePrefix = "AcOnoffState_"
    sAcWorkTimePrefix = "AcWorkTime_"
    sAcDeliveryTempPrefix = "AcDeliveryTemp_"
    sAcReturnTempPrefix = "AcReturnTemp_"
    sAcSetTempPrefix = "AcSetTemp_"
    sRackXPosPrefix = "RackXPos_"
    sRackYPosPrefix = "RackYPos_"
    sAcXPosPrefix = "AcXPos_"
    sAcYPosPrefix = "AcYPos_"
    sXPosMin = "XPosMin"
    sXPosMax = "XPosMax"
    sYPosMin = "YPosMin"
    sYPosMax = "YPosMax"
    sRackColdTempPrefix = "RackColdTemp_"
    sRackHotTempPrefix = "RackHotTemp_"
    sColdTempMean = "ColdTempMean"
    sHotTempMean = "HotTempMean"
    
    sTargetTemp = "TargetTemp"
    sTargetTempDeadThresh = "TargetTempDeadThresh"
    sAcWorkNumberMin = "AcWorkNumberMin"
    sAcTempSetThresh = "AcTempSetThresh"
    sTargetDeliveryReturnDiff = "TargetDeliveryReturnDiff"
    
    sSettingParam = "SettingParam"
    sAcgStateParam = "AcgStateParam"
    sParamLabel = "ParamLabel"
    sParamData = "ParamData"
    sStatus = "Status"
    sPredictAction = "PredictAction"
    sEquipIdArray = "EquipIdArray"
    sPredOnoffArray = "PredOnoffArray"
    sPredTempSetArray = "PredTempSetArray"
